nodeLinker: node-modules
packageExtensions:
  "@phenomnomnominal/tsquery@*":
    dependencies:
      typescript: "*"
  "url-loader@*":
    dependencies:
      "webpack": "*"
  "framer-motion-3d@*":
    dependencies:
      "@react-three/fiber": "8.0.12"

